### ISSUE TITLE
Can not work with unicode string

### ISSUE THREAD

**Issue by dminh** [TimKam/compound-word-splitter#1]
It fails when splitting the unicode string, such as: u'Anlagenbuchhalterin'. Please fix it. This is my suggestion:
import enchant

def __concat(object1, object2):
    if isinstance(object1, str) or isinstance(object1, unicode):
        object1 = [object1]
    if isinstance(object2, str) or isinstance(object2, unicode):
        object2 = [object2]
    return object1 + object2

**Comment by TimKam** [comment]
Thanks for reporting this issue. It only occurs with Python 2.x. Fixed it and re-release now.
