### ISSUE TITLE
Inconsistent return type

### ISSUE THREAD

**Issue by marius-plutoflume** [TimKam/compound-word-splitter#3]
The result of the split method returns different types. As described in the documentation it can return an empty string or a list but it can as well return just an upper cased word. 
This inconsistency makes it a bit cumbersome to use and I dont see a benefit over always return a list. Besides that, I think it could be beneficial for the performance of that algorithm as the type of return value does not need to be checked over and over again.
An idea could be:
Instead of returning an empty string, one could return an empty array. Instead of returning a word, return an array with that word.

**Comment by TimKam** [comment]
Makes sense to me. PRs are welcome :-) I won't have time to work on this right now (possible at a later point).
